### PR TITLE
Fixed a bug where children of states entered from transitions would not have their entry actions or invocations typed properly

### LINKED ISSUE #124: Bug:   eventsCausingServices in *.typegen.ts does not type parallel types correctly
### Description

When using parallel states, service signatures are incorrectly typed. 

eventsCausingServices have the value 'xstate.init'.

repro:
See https://codesandbox.io/s/quirky-poincare-wlofi4

### Expected result

```
eventsCausingServices: {
    off: 'GO_NUMBER' | 'GO_STRING';
    jump: 'GO_STRING';
  };
```

### Actual result

```
eventsCausingServices: {
    off: 'GO_NUMBER';
    jump: 'xstate.init';
  };
```
TypeScript Error:
```
This condition will always return 'false' since the types '"xstate.init"' and '"GO_STRING"' have no overlap.
```

### Reproduction

https://codesandbox.io/s/quirky-poincare-wlofi4

### Additional context

Sorry I couldn't get codesandbox to work with typegen.

### PR DESCRIPTION
**Pull request by mattpocock**
Fixes #124

### CODE REVIEW

**Comment by mattpocock** [comment]
Fixes #124

**Comment by Andarist** [comment]
@mattpocock to make GitHub auto-close the referenced issue you must put this "fixes #XXX" comment in the description of the PR itself, it doesn't work if you use this in some latter comment

**Comment by mattpocock** [comment]
Gotcha, it works that way in Linear so I'm getting confused

File: packages/shared/src/__tests__/__examples__/parallel.ts [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    initial: "idle",
+    states: {
+      idle: {
+        on: {
+          GO_STRING: {
+            target: "doesnt",
+          },
+          GO_NUMBER: {
+            target: "works",
+          },
```
Comment (Andarist) [inline packages/shared/src/__tests__/__examples__/parallel.ts:30]: everything related to this transition is redundant here and somewhat makes analyzing the intent of this test harder

File: packages/shared/src/__tests__/__examples__/parallel.ts [hunk 2]
```diff
@@ -0,0 +1,71 @@
+import { createMachine } from "xstate";
```
Comment (Andarist) [inline packages/shared/src/__tests__/__examples__/parallel.ts:1]: since you have added fixes for both invokes and entry actions - it would be great to have dedicated tests for both of those in combination with parallel states. At the moment only invoke case got its test here.

File: packages/shared/src/introspectMachine.ts [hunk 3]
```diff
@@ -191,31 +191,40 @@ export const introspectMachine = (machine: XState.StateNode) => {
...
-              transition.eventType,
-              node.path,
-            );
+          /**
+           * We gather info on all the invocations that begin on
+           * all the nodes that are initial state nodes of the children
+           * of this node (see recursive-invoke)
+           */
+
+          const nodesToGather = [targetNode, ...targetNode.initialStateNodes];
```
Comment (Andarist) [inline packages/shared/src/introspectMachine.ts:214]: note: the logic in this file doesn't handle history nodes at all - so that should be fixed as well, but in a separate PR

File: packages/shared/src/__tests__/__examples__/parallel.ts (hunk 2 above)
Comment (mattpocock) [reply packages/shared/src/__tests__/__examples__/parallel.ts:1]: I'll remove this test, this was copied from a user's submission.

Comment (Andarist) [reply packages/shared/src/__tests__/__examples__/parallel.ts]: It was a good test though (if it would be slimmed down) :p resolving compound states recursively and resolving all child states of a parallel state is different. Right now they are both kinda resolved automatically using the same internal thing but we can't guarantee that this will always be the case. So it would be better to have separate tests here for both cases

Comment (mattpocock) [reply packages/shared/src/__tests__/__examples__/parallel.ts:1]: Re-added

**Review by Andarist — APPROVED** [review]
